name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build
      run: echo "Building project"

title: Developer Blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dntstck.github.io" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown
