name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build
      run: echo "Building project"

title: Developer Blog
description: "Welcome to my blog!"
baseurl: "/blog" # Ensures subpath is used
url: "https://dntstck.co.uk"
theme: minima
markdown: kramdown

