name: Schedule Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight. 
  push:
    paths:
      - 'scheduled/**'

  workflow_dispatch:
jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Run scheduling script
      run: node deploy/schedulePosts.js
